###############################################################################
#
#     Snakefile - Allele specific expression using ASElux
#
#
###############################################################################

shell.prefix("set -eo pipefail; echo BEGIN at $(date); ")
shell.suffix("; exitstat=$?; echo END at $(date); echo exit status was $exitstat; exit $exitstat")

configfile: "../config/config.yaml"

include: "rules/fastq_prep.smk"

import numpy
import pandas as pd
import os
import json

# -------  LOAD SAMPLE LIST  ---------

sample_file = config['sample_list']
sample_df = pd.read_table(sample_file, sep="\t+", header=0)
sampleID = sample_df.sampleID
fastq = sample_df.fastq


#FILES = json.load(open(config['SAMPLES_JSON']))
MERGE_FILES = json.load(open(config['MERGE_FILES_JSON']))
#print()
ALL_SAMPLES = sorted(MERGE_FILES.keys())
ALL_MERGED_SAMPLES = sorted(MERGE_FILES.keys()) 
print(ALL_MERGED_SAMPLES)


# -------------  RULES  --------------

localrules: move_and_rename_fastqs

rule all:
    input:
#        expand("../results/01RAW_fqs/{sample}", sample = sample_df.sampleID),
         expand("../results/02ZIPPED_fqs/{sample}", sample = sample_df.sampleID),
         expand("../results/03MRGD_fqs/{sampleID}_R2.fastq.gz", sampleID = ALL_MERGED_SAMPLES),
         expand("../results/04FASTQC/pre-trimmed/{sampleID}_R2_fastqc.zip", sampleID = ALL_MERGED_SAMPLES),
         "../results/05MULTIQC/pre-trimmed/multiQC_log.html",
         expand("../results/04FASTQC/trimmed_mrg/{sampleID}_val_2_fastqc.zip", sampleID = ALL_MERGED_SAMPLES),
#         expand("../results/07HARDTRIM_fqs/{sampleID}_val_2.fq.gz", sampleID = ALL_MERGED_SAMPLES),
#         expand("../results/07HARDTRIM_fqs/{sampleID}_val_1.noSR.fq.gz", sampleID = ALL_MERGED_SAMPLES),
         expand("../results/08READ_DISTRIBUTION/trimmed/{sampleID}_R2_readDist.txt", sampleID = ALL_MERGED_SAMPLES),
         expand("../results/08READ_DISTRIBUTION/hrd_trm_noSR/{sampleID}_R2_readDist.txt", sampleID = ALL_MERGED_SAMPLES)
