###############################################################################
#
#     Snakefile - Allele specific expression using ASElux
#
#
###############################################################################

shell.prefix("set -eo pipefail; echo BEGIN at $(date); ")
shell.suffix("; exitstat=$?; echo END at $(date); echo exit status was $exitstat; exit $exitstat")

configfile: "../config/config.yaml"

include: "rules/fastq_prep.smk"

import numpy
import pandas as pd
import os


# -------  LOAD SAMPLE LIST  ---------

sample_file = config['sample_list']
sample_df = pd.read_table(sample_file, sep="\t+", header=0)
sampleID = sample_df.sampleID
fastq = sample_df.fastq


# -------------  RULES  --------------

localrules: move_and_rename_fastqs

rule all:
    input:
#        expand("01RAW_fqs/{sample}", sample = sample_df.sampleID),
#         expand("02ZIPPED_fqs/{sample}", sample = sample_df.sampleID),
         expand("03MRGD_fqs/{sampleID}_R2.fastq.gz", sampleID = ALL_MERGED_SAMPLES),
