__default__:
    num_cores: 1
    total_mem: 5G
    duration: 0-2:00:00
fastqc:
    num_cores: 1
    total_mem: 8G
build_static_index:
    num_cores: 1
    total_mem: 40G
trim_fastq:
    num_cores: 15 # Doesn't match threads in script see https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md
    total_mem: 30G
ase_align:
    num_cores: 1
    total_mem: 60G
