__default__:
    num_cores: 1
    mem_per_core: 5G
fastqc:
    num_cores: 1
    mem_per_core: 8G
build_static_index:
    num_cores: 1
    mem_per_core: 40G
trim_fastq:
    num_cores: 15 # Doesn't match threads in script see https://github.com/FelixKrueger/TrimGalore/blob/master/Docs/Trim_Galore_User_Guide.md
    mem_per_core: 2G
ase_align:
    num_cores: 1
    mem_per_core: 10G
